version: "3.8"

services:
  user-db:
    image: postgres:14-alpine
    container_name: user-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=users
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/users/data

  user_app:
    image: epaminaprymava/users-app:1.0.0
    container_name: user-service
    environment:
      - DB_URL=r2dbc:postgresql://user-db:5432/users
      - DB_USERNAME=postgres
      - DB_PASSWORD=admin
    ports:
      - "8081:8081"
    depends_on:
      - user-db

  post-db:
    image: postgres:14-alpine
    container_name: post-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=posts
    ports:
      - "5433:5432"
    volumes:
      - pg-data:/var/lib/postgresql/posts/data  

  post_app:
    image: epaminaprymava/posts-app:1.0.0
    container_name: post-service
    environment:
      - DB_URL=r2dbc:postgresql://post-db:5432/posts
      - DB_USERNAME=postgres
      - DB_PASSWORD=admin
      - REMOTE_SERVICE_BASE_URL=http://user-service:8081
    ports:
      - "8082:8082"
    depends_on:
      - post-db

volumes:
  pg-data:
