apiVersion: v1
kind: Namespace
metadata:
  name: k8s-program

---

apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: k8s-program
spec:
  type: LoadBalancer
  selector:
    app: user-service-pod
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: k8s-program
spec:
  selector:
    matchLabels:
      app: user-service-pod
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: user-service-pod
        owner: epaminaprymava
    spec:
      containers:
        - name: users-app
          image: epaminaprymava/users-app:2.0.0
          ports:
            - containerPort: 8081
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: users-database-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-database-secret
                  key: password
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: users-database-secret
                  key: url
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: k8s-program
spec:
  type: LoadBalancer
  selector:
    app: post-service-pod
  ports:
    - protocol: "TCP"
      port: 8082
      targetPort: 8082

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  namespace: k8s-program
spec:
  selector:
    matchLabels:
      app: post-service-pod
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: post-service-pod
        owner: epaminaprymava
    spec:
      containers:
        - name: posts-app
          image: epaminaprymava/posts-app:2.0.0
          ports:
            - containerPort: 8082
          env:
            - name: REMOTE_SERVICE_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: post-configuration-app
                  key: application_properties_file_name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: posts-database-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: posts-database-secret
                  key: password
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: posts-database-secret
                  key: url
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 20 
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5