apiVersion: v1
kind: Namespace
metadata:
  name: k8s-program

---

apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: k8s-program
spec:
  type: LoadBalancer
  selector:
    app: user-service-pod
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: k8s-program
spec:
  selector:
    matchLabels:
      app: user-service-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: user-service-pod
        owner: epaminaprymava
    spec:
      containers:
        - name: users-app
          image: epaminaprymava/users-app:1.0.0
          ports:
            - containerPort: 8081
          env:
            - name: DB_URL
              value: r2dbc:postgresql://user-db:5432/users
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: admin

---

apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: k8s-program
spec:
  type: LoadBalancer
  selector:
    app: post-service-pod
  ports:
    - protocol: "TCP"
      port: 8082
      targetPort: 8082

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  namespace: k8s-program
spec:
  selector:
    matchLabels:
      app: post-service-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: post-service-pod
        owner: epaminaprymava
    spec:
      containers:
        - name: posts-app
          image: epaminaprymava/posts-app:1.0.0
          ports:
            - containerPort: 8082
          env:
            - name: DB_URL
              value: r2dbc:postgresql://post-db:5432/posts
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: admin
            - name: REMOTE_SERVICE_BASE_URL
              value: http://user-service:8081