apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-postgres-local-pv
  namespace: k8s-program
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: db-local-storage
  local:
    path: /usr/share
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - docker-desktop

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: db-local-storage
  namespace: k8s-program
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-postgres-pvc
  namespace: k8s-program
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
  storageClassName: db-local-storage