apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: users-database-secret
  namespace: k8s-program
stringData:
  username: postgres
  password: admin
  url: r2dbc:postgresql://user-db:5432/users
  dbname: users

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: posts-database-secret
  namespace: k8s-program
stringData:
  username: postgres
  password: admin
  url: r2dbc:postgresql://post-db:5432/posts
  dbname: posts